### ISSUE TITLE
Error on Minifing

### ISSUE THREAD

**Issue by SimplySayHi** [thaneuk/brackets-js-minifier-offline#1] opened 2017-09-28 20:57 UTC
In brackets dev tool I can see this error when I try to minify a js file:

NodeDebugUtils.js:111 [node-error 10:52:50 PM] minifyFile:exec error: Error: Command failed: java -jar "/pathToBracketsExtensions/extensions/user/js-minifier-offline-google-closure/google.closure.compiler/closure-compiler-v20170521.jar"  --compilation_level SIMPLE_OPTIMIZATIONS  --js "/pathToFile/file.js" --js_output_file "/pathToFile/file.min.js"
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by thaneuk** [comment] 2017-09-28 21:47
Looks like a possible issue with the Google minification jar file and your version of Java.

Can you reply with OS and Java runtime version so I can look into it further.

Please ensure your version of Java is the latest.

**Comment by SimplySayHi** [comment] 2017-09-28 22:08
Hi,
I'm running OSX Yosemite 10.10.5 and installed Java 8 update 144 (as I see from the preferences and it is the latest).

**Comment by thaneuk** [comment] 2017-09-29 17:27
I tried and can't reproduce the issue.  I've updated the extension with the latest google closure compiler jar to see if that helps.

If you don't have any luck with the update try manually using the jar file with the js file.

You may need to report the bug directly, I would suggest starting with the discussion group https://groups.google.com/forum/#!forum/closure-compiler-discuss

**Comment by thaneuk** [comment] 2017-10-07 17:17
With nothing further after a week I'm going to close this.

**Closed as completed by thaneuk** 2017-10-07 17:17 UTC
